[package]
name = "godaddy-dns-updater"
version = "0.1.0"
authors = ["Ryan Macdonald <macdonaldr93@gmail.com>"]

[dependencies]
clap = "2.29.0"
futures = "0.1"
hyper = "0.11"
hyper-tls = "0.1.2"
tokio-core = "0.1"
serde_json = "1.0"
curl = "0.4"
